name: Deploy printer dashboard

on:
  repository_dispatch:
    types: [update-status]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build folder
        run: mkdir site

      - name: Generate status.json
        run: |
          echo '${{ toJson(github.event.client_payload.status) }}' > site/status.json

      - name: Add frontend
        run: |
          cp public/index.html site/
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
          retention-days: 1

      # - name: Configure Pages
      #   uses: actions/configure-pages@v5

      # - name: Upload Pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: public
      #     retention-days: 1

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4